;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        kill-region
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        indent-for-tab-command
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))
